// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PieShop.Models;

namespace PieShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220819002458_pieupdate")]
    partial class pieupdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PieShop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Des")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Fruit pies"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "cheese cake"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "seasonal pies"
                        });
                });

            modelBuilder.Entity("PieShop.Models.Pie", b =>
                {
                    b.Property<int>("PieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllergyInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPieOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Pies");

                    b.HasData(
                        new
                        {
                            PieId = 1,
                            CategoryId = 1,
                            ImgUrl = "https://i0.wp.com/sweetlycakes.com/wp-content/uploads/2019/12/Apple-Pie-8blog.jpg?fit=1440%2C2160&ssl=1",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDes = "Long description",
                            Name = "apple",
                            Price = 12.32m,
                            ShortDes = "short description"
                        },
                        new
                        {
                            PieId = 2,
                            CategoryId = 3,
                            ImgUrl = "https://i0.wp.com/sweetlycakes.com/wp-content/uploads/2019/12/Apple-Pie-8blog.jpg?fit=1440%2C2160&ssl=1",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDes = "Long description",
                            Name = "orange",
                            Price = 12.32m,
                            ShortDes = "short description"
                        },
                        new
                        {
                            PieId = 3,
                            CategoryId = 2,
                            ImgUrl = "https://i0.wp.com/sweetlycakes.com/wp-content/uploads/2019/12/Apple-Pie-8blog.jpg?fit=1440%2C2160&ssl=1",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDes = "Long description",
                            Name = "cake",
                            Price = 12.32m,
                            ShortDes = "short description"
                        },
                        new
                        {
                            PieId = 4,
                            CategoryId = 2,
                            ImgUrl = "https://i0.wp.com/sweetlycakes.com/wp-content/uploads/2019/12/Apple-Pie-8blog.jpg?fit=1440%2C2160&ssl=1",
                            InStock = true,
                            IsPieOfTheWeek = true,
                            LongDes = "Long description",
                            Name = "cake",
                            Price = 12.32m,
                            ShortDes = "short description"
                        });
                });

            modelBuilder.Entity("PieShop.Models.Pie", b =>
                {
                    b.HasOne("PieShop.Models.Category", "Category")
                        .WithMany("pies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
